# Generated by Django 4.1.2 on 2022-11-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='ownership_proof',
            new_name='license_proof',
        ),
    ]
