# Generated by Django 4.1.2 on 2022-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0002_alter_doctor_clinic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor-image'),
        ),
    ]
