# Generated by Django 4.1.2 on 2022-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0002_rename_ownership_proof_doctor_license_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='province',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
