# Generated by Django 4.1.2 on 2022-12-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0002_doctor_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک شنبه'), (2, 'دو شنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنج شنبه'), (6, 'جمعه')])),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_management.doctor')),
            ],
        ),
    ]
