# Generated by Django 4.1.2 on 2022-11-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0003_doctor_city_doctor_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='is_verifyed',
            new_name='is_active',
        ),
    ]
