# Generated by Django 4.1.2 on 2022-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0004_doctor_education_doctor_office_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default=False, unique=True),
        ),
    ]
