# Generated by Django 4.1.2 on 2022-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0005_rename_natinal_code_doctor_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
