# Generated by Django 4.1.2 on 2022-10-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalOwner',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_hospital_owner',
            new_name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_normal_user',
        ),
    ]
