# Generated by Django 4.1.2 on 2022-10-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='hospital-proof-of-ownership'),
        ),
        migrations.AlterField(
            model_name='hotelowner',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='hotel-proof-of-ownership'),
        ),
    ]
