# Generated by Django 4.1.2 on 2022-11-12 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_proof', models.FileField(blank=True, null=True, upload_to='hotel-proof-of-ownership')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hotel_owner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='HotelOwner',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
