# Generated by Django 4.1.2 on 2022-11-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_is_doctor_alter_user_is_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='doctor-proof-of-being-doctor'),
        ),
    ]
