# Generated by Django 4.1.2 on 2022-11-12 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_hotel_alter_user_is_doctor_alter_user_is_hotel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_stars',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rules',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
