# Generated by Django 4.1.2 on 2022-11-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_hotel_address_hotel_hotel_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
