# Generated by Django 4.1.2 on 2022-11-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_specialty_doctor_clinic_address_doctor_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelowner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='HotelOwner',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
