# Generated by Django 4.1.2 on 2022-11-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_hotelowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelowner',
            name='test',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
