# Generated by Django 4.1.2 on 2022-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_hotelowner_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelowner',
            old_name='test',
            new_name='shaba_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
