# Generated by Django 4.1.2 on 2022-11-27 13:55

from django.db import migrations, models
import hotel_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cover_image',
            field=models.ImageField(blank=True, default=hotel_management.models.get_default_hotel_image_cover, null=True, upload_to='hotel-images'),
        ),
    ]
