# Generated by Django 4.1.2 on 2022-11-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('hotel_management', '0002_hotel_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='authentication.hotelowner'),
        ),
    ]
