# Generated by Django 4.1.2 on 2022-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0002_room_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed_count',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
