# Generated by Django 4.1.2 on 2022-11-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0003_alter_room_bed_count_alter_room_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='is_cover',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='is_thumbnail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
