# Generated by Django 4.1.2 on 2022-11-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0004_alter_roomimage_is_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
