# Generated by Django 4.1.2 on 2022-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0005_alter_hotel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(related_name='features', to='hotel_management.feature'),
        ),
    ]
