# Generated by Django 4.1.2 on 2022-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0006_feature_hotel_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ownership_proof',
        ),
        migrations.AddField(
            model_name='hotel',
            name='senfi_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='hotel_management.feature'),
        ),
    ]
