# Generated by Django 4.1.2 on 2022-11-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0007_remove_hotel_ownership_proof_hotel_senfi_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='senfi_code',
            new_name='trade_code',
        ),
    ]
