# Generated by Django 4.1.2 on 2022-11-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_hotelowner'),
        ('hotel_management', '0008_rename_senfi_code_hotel_trade_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='authentication.hotelowner'),
        ),
    ]
